spring.application.name=cancha
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/club_deportivo
spring.datasource.username=root
spring.datasource.password=211822

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true