spring.application.name=reservas
server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/basereserva}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

canchas.service.url=${CANCHAS_SERVICE_URL:http://localhost:8081}